add register, login and post order handlers
kartalenka7/project_gophermart pull request #1
Opened 2023-06-12 15:42 UTC by kartalenka7

2023-06-21 09:20 UTC, bambruysk requested changes
Нужно немного дорабоать и будет готово

2023-06-21 09:20 UTC, bambruysk commented on internal/config/logging.go
> +}
Логггеры и утилиты лучше вынести в отдельные пакеты

2023-06-21 09:20 UTC, bambruysk commented on internal/handlers/handlers.go
> +	RgstrUser(ctx context.Context, user model.User) error
не надо экономить на буквах)

2023-06-21 09:20 UTC, bambruysk commented on internal/handlers/handlers.go
> +
Обрати внимание что это кусочек кода повторяется - можно вынести в отдельную функцию

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +	db.pgxPool.Close()
здесь кажется может вернуться ошибка

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +func (db *DBStruct) GetUser(ctx context.Context, user model.User) error {
Get - но возвращает только ошибку. Что-то не так

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +	}
вот это должно быть в сервисе

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +	login := ctx.Value(model.KeyLogin).(string)
если кастим к типу так, то лучше проверять можно ли это сделать

login, ok := ctx.Value(model.KeyLogin).(string)
if !ok {
//////
}

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +func (db *DBStruct) GetOrders(ctx context.Context) ([]model.OrdersResponse, error) {
вообще не очень хорошо логин пользоваателя передавать в контексте до сюда. Его лучше вынуть отттуда прямо в хендлерах и дальше передавать явно

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +	sort.SliceStable(orders, func(i, j int) bool {
можно сделать это в SQL  -  ORDER BY

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +		db.log.WithFields(logrus.Fields{"balance": balance}).Info("Накапливаем баланс")
Вот это тоже должно быть в сервисе - 
По сути репозиторий должен отдать список начислений и списаний пользователя ( как в бухгалтерии)
В сервисе мы видим что можно списать, и тогда делаем команду на списание. Если бы у нас был нагруженный сервис, то вероятно мы бы применили какие-то дополнительне действия

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +			rows, err := pgxPool.Query(ctx, selectProcessingOrders, "INVALID", "PROCESSED")
Тут слишком длинный метод, сопровохждать такое больно и сложно.

Вообще эту джобу стоит вынести на слой сервисов, где она отдельно крутится и спрашивает storage и accrual

2023-06-21 09:20 UTC, bambruysk commented on internal/storage/storage.go
> +
вот это в отдельный метод точно и на сервис, почему у нас хранилище вообще должно знать об accrual

2023-06-22 08:32 UTC, kartalenka7 commented on internal/storage/storage.go
> +	db.pgxPool.Close()
не, в [документации](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool#Pool.Close)
func (p *Pool) Close()

2023-06-24 05:43 UTC, kartalenka7 commented on internal/storage/storage.go
> +	sort.SliceStable(orders, func(i, j int) bool {
в бд время хранится в текстовом представлении, потому что после  time.Now().Format(time.RFC3339)  string получаем

2023-06-29 08:37 UTC, bambruysk approved these changes
Хорощо. Доработай замечания и можно сливать

2023-06-29 08:37 UTC, bambruysk commented on cmd/gophermart/main.go
> +	time.AfterFunc(60*time.Second, cancel)
А зачем это?

Если контекст с таймаутом, то он сам отменится. Если мы вышли из программы по каким то другим причинам, то тогда лучше и надежнее использовать defer cancel()

2023-06-29 08:37 UTC, bambruysk commented on internal/handlers/handlers.go
> +	login, ok := r.Context().Value(model.KeyLogin).(string)
лучше бы это обернуть в функцию типа func GetUser(r * http.Request) (login string, err error) Это более универсаьный метод и часто используется во всяких фреймворках и пакетах 

Например, мы решили что логин будет передаваться в каком-то хидере, или еше как-то ( не через контекст) - тогда это не потребует доработок этих хэндлеров

2023-06-29 08:37 UTC, bambruysk commented on internal/service/service.go
> +			client := &http.Client{}
Клиента можно не создавать заново каждый раз

кстати есть удобная библиотека клиента https://github.com/go-resty/resty - Она сильно может упростить жизнь в этом месте

2023-06-29 08:37 UTC, bambruysk commented on internal/service/service.go
> +				decoder := json.NewDecoder(resp.Body)
А если вернулся статус не 200? нужно добавить проверку. 

И еще - accrual может вернуть 429 - то есть слишком много запросов, и тогда нужно прекратить запросы к нему на некоторое время ( он указывает это время в ответе) Важно обрабатывать этот момент, все зависнет

2023-06-29 08:37 UTC, bambruysk commented on internal/service/service.go
> +				url := accrualSys + "/api/orders/" + v
здесь лучше использовать path.Join()

2023-08-14 15:30 UTC, merged